server:
  port: 9001

spring:
  application:
    name: microservice-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhaozhe123
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka,http://127.0.0.1:9999/eureka
    instance:
      prefer-ip-address: true #优先使用ip注册到eureka
      lease-expiration-duration-in-seconds: 90  #服务失效时间
      lease-renewal-interval-in-seconds: 30   #服务续约间隔
      #健康检查
      healthcheck:
        enabled: true